version: 2
jobs:

  # In stall project dependencies and cache
  build:
    docker:
      - image: patheard/node-puppeteer:latest
    steps:
      - checkout
      - run: npm install

  # Behaviour tests against locally running service using JEST
  behaviour_test:
    docker:
      - image: patheard/node-puppeteer:latest
    steps:
      - run:
          command: |
            npm run test-server &
            wget --retry-connrefused --tries 30 --waitretry 3 -qO- http://localhost:8080 &> /dev/null # Wait until the website is up before continuing
            npm start

  # Security audits with npm audit
  security_test:
    docker:
      - image: patheard/node-puppeteer:latest
    steps:
      - run: npm audit  

  # Unit tests using JEST
  unit_test:
    docker:
      - image: patheard/node-puppeteer:latest
    steps:
      - run:
          command: |
            npm run test-server &
            wget --retry-connrefused --tries 30 --waitretry 3 -qO- http://localhost:8080 &> /dev/null # Wait until the website is up before continuing
            npm test

# Define job flow, dependencies and filters (when the job should run)
workflows:
  version: 2
  test:
    jobs:
      - build
      - behaviour_test:
          requires:
            - build
      - unit_test:
          requires:
            - build
      - security_test:
          requires:
            - build